import Footer from './(components)/Footer/Footer'
import Navigation from './(components)/Navigation/Navigation'
import './globals.css'

import { Inter, JetBrains_Mono } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] })


const JetBrains = JetBrains_Mono({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const navdata = [
  {
      "title": "Home",
      "path": "/"
  },
  {
      "title": "Contacts",
      "path": "/contacts"
  },
  {
      "title": "Layout",
      "path": "/layout"
  }
]



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={JetBrains.className}>

      
        <Navigation data={navdata} show={true}/>

        {children}

        <Footer data={navdata}/>

        </body>
    </html>
  )
}
