
import Footer from '@/components/Footer/Footer';
import Navigation from '../components/Navigation/Navigation'
import './globals.css'

import { Inter, JetBrains_Mono } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] })


const JetBrains = JetBrains_Mono({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const navData = [
  {
      "title": "Home",
      "path": "/"
  },
  {
      "title": "Contacts",
      "path": "/contacts"
  },
  {
      "title": "Icons",
      "path": "/icons"
  },
  {
      "title": "Gastropub",
      "path": "/gastropub"
  }
]



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={JetBrains.className}>
      GLOBAL LAYOUT FIL
        <Navigation data={navData} show={true}/>

        {children}
      
        <Footer navData={navData}/>

        </body>
    </html>
  )
}
